var annotated_dup =
[
    [ "simics", "namespacesimics.html", [
      [ "detail", "namespacesimics_1_1detail.html", [
        [ "attr_from_std_helper", "structsimics_1_1detail_1_1attr__from__std__helper.html", null ],
        [ "attr_from_std_helper< attr_value_t >", "structsimics_1_1detail_1_1attr__from__std__helper_3_01attr__value__t_01_4.html", null ],
        [ "attr_from_std_helper< bool >", "structsimics_1_1detail_1_1attr__from__std__helper_3_01bool_01_4.html", null ],
        [ "attr_from_std_helper< ConfObjectRef >", "structsimics_1_1detail_1_1attr__from__std__helper_3_01ConfObjectRef_01_4.html", null ],
        [ "attr_from_std_helper< const char * >", "structsimics_1_1detail_1_1attr__from__std__helper_3_01const_01char_01_5_01_4.html", null ],
        [ "attr_from_std_helper< data_attribute >", "structsimics_1_1detail_1_1attr__from__std__helper_3_01data__attribute_01_4.html", null ],
        [ "attr_from_std_helper< std::array< V, N > >", "structsimics_1_1detail_1_1attr__from__std__helper_3_01std_1_1array_3_01V_00_01N_01_4_01_4.html", null ],
        [ "attr_from_std_helper< std::deque< V > >", "structsimics_1_1detail_1_1attr__from__std__helper_3_01std_1_1deque_3_01V_01_4_01_4.html", null ],
        [ "attr_from_std_helper< std::list< V > >", "structsimics_1_1detail_1_1attr__from__std__helper_3_01std_1_1list_3_01V_01_4_01_4.html", null ],
        [ "attr_from_std_helper< std::map< X, Y > >", "structsimics_1_1detail_1_1attr__from__std__helper_3_01std_1_1map_3_01X_00_01Y_01_4_01_4.html", null ],
        [ "attr_from_std_helper< std::pair< X, Y > >", "structsimics_1_1detail_1_1attr__from__std__helper_3_01std_1_1pair_3_01X_00_01Y_01_4_01_4.html", null ],
        [ "attr_from_std_helper< std::string >", "structsimics_1_1detail_1_1attr__from__std__helper_3_01std_1_1string_01_4.html", null ],
        [ "attr_from_std_helper< std::vector< V > >", "structsimics_1_1detail_1_1attr__from__std__helper_3_01std_1_1vector_3_01V_01_4_01_4.html", null ],
        [ "attr_getter_helper", "structsimics_1_1detail_1_1attr__getter__helper.html", null ],
        [ "attr_getter_helper< T &(*)(O &)>", "structsimics_1_1detail_1_1attr__getter__helper_3_01T_01_6_07_5_08_07O_01_6_08_4.html", null ],
        [ "attr_getter_helper< T O::* >", "structsimics_1_1detail_1_1attr__getter__helper_3_01T_01O_1_1_5_01_4.html", null ],
        [ "attr_getter_helper< T(*)(O &)>", "structsimics_1_1detail_1_1attr__getter__helper_3_01T_07_5_08_07O_01_6_08_4.html", null ],
        [ "attr_getter_helper< T(O::*)() const >", "structsimics_1_1detail_1_1attr__getter__helper_3_01T_07O_1_1_5_08_07_08_01const_01_4.html", null ],
        [ "attr_getter_helper< T(O::*)()>", "structsimics_1_1detail_1_1attr__getter__helper_3_01T_07O_1_1_5_08_07_08_4.html", null ],
        [ "attr_getter_helper_dual", "structsimics_1_1detail_1_1attr__getter__helper__dual.html", null ],
        [ "attr_getter_helper_dual< T O::*, C >", "structsimics_1_1detail_1_1attr__getter__helper__dual_3_01T_01O_1_1_5_00_01C_01_4.html", null ],
        [ "attr_getter_helper_dual< T(O::*)() const, C >", "structsimics_1_1detail_1_1attr__getter__helper__dual_3_01T_07O_1_1_5_08_07_08_01const_00_01C_01_4.html", null ],
        [ "attr_getter_helper_dual< T(O::*)(), C >", "structsimics_1_1detail_1_1attr__getter__helper__dual_3_01T_07O_1_1_5_08_07_08_00_01C_01_4.html", null ],
        [ "attr_list_type_str_helper", "structsimics_1_1detail_1_1attr__list__type__str__helper.html", null ],
        [ "attr_setter_helper", "structsimics_1_1detail_1_1attr__setter__helper.html", null ],
        [ "attr_setter_helper< T &(*)(O &)>", "structsimics_1_1detail_1_1attr__setter__helper_3_01T_01_6_07_5_08_07O_01_6_08_4.html", null ],
        [ "attr_setter_helper< T O::* >", "structsimics_1_1detail_1_1attr__setter__helper_3_01T_01O_1_1_5_01_4.html", null ],
        [ "attr_setter_helper< void(*)(O &, T &)>", "structsimics_1_1detail_1_1attr__setter__helper_3_01void_07_5_08_07O_01_6_00_01T_01_6_08_4.html", null ],
        [ "attr_setter_helper< void(*)(O &, T)>", "structsimics_1_1detail_1_1attr__setter__helper_3_01void_07_5_08_07O_01_6_00_01T_08_4.html", null ],
        [ "attr_setter_helper< void(O::*)(T &)>", "structsimics_1_1detail_1_1attr__setter__helper_3_01void_07O_1_1_5_08_07T_01_6_08_4.html", null ],
        [ "attr_setter_helper< void(O::*)(T)>", "structsimics_1_1detail_1_1attr__setter__helper_3_01void_07O_1_1_5_08_07T_08_4.html", null ],
        [ "attr_setter_helper_dual", "structsimics_1_1detail_1_1attr__setter__helper__dual.html", null ],
        [ "attr_setter_helper_dual< T O::*, C >", "structsimics_1_1detail_1_1attr__setter__helper__dual_3_01T_01O_1_1_5_00_01C_01_4.html", null ],
        [ "attr_setter_helper_dual< void(O::*)(T &), C >", "structsimics_1_1detail_1_1attr__setter__helper__dual_3_01void_07O_1_1_5_08_07T_01_6_08_00_01C_01_4.html", null ],
        [ "attr_setter_helper_dual< void(O::*)(T), C >", "structsimics_1_1detail_1_1attr__setter__helper__dual_3_01void_07O_1_1_5_08_07T_08_00_01C_01_4.html", null ],
        [ "attr_to_std_helper", "structsimics_1_1detail_1_1attr__to__std__helper.html", null ],
        [ "attr_to_std_helper< attr_value_t >", "structsimics_1_1detail_1_1attr__to__std__helper_3_01attr__value__t_01_4.html", null ],
        [ "attr_to_std_helper< bool >", "structsimics_1_1detail_1_1attr__to__std__helper_3_01bool_01_4.html", null ],
        [ "attr_to_std_helper< ConfObjectRef >", "structsimics_1_1detail_1_1attr__to__std__helper_3_01ConfObjectRef_01_4.html", null ],
        [ "attr_to_std_helper< const char * >", "structsimics_1_1detail_1_1attr__to__std__helper_3_01const_01char_01_5_01_4.html", null ],
        [ "attr_to_std_helper< data_attribute >", "structsimics_1_1detail_1_1attr__to__std__helper_3_01data__attribute_01_4.html", null ],
        [ "attr_to_std_helper< std::array< V, N > >", "structsimics_1_1detail_1_1attr__to__std__helper_3_01std_1_1array_3_01V_00_01N_01_4_01_4.html", null ],
        [ "attr_to_std_helper< std::deque< V > >", "structsimics_1_1detail_1_1attr__to__std__helper_3_01std_1_1deque_3_01V_01_4_01_4.html", null ],
        [ "attr_to_std_helper< std::list< V > >", "structsimics_1_1detail_1_1attr__to__std__helper_3_01std_1_1list_3_01V_01_4_01_4.html", null ],
        [ "attr_to_std_helper< std::map< X, Y > >", "structsimics_1_1detail_1_1attr__to__std__helper_3_01std_1_1map_3_01X_00_01Y_01_4_01_4.html", null ],
        [ "attr_to_std_helper< std::pair< X, Y > >", "structsimics_1_1detail_1_1attr__to__std__helper_3_01std_1_1pair_3_01X_00_01Y_01_4_01_4.html", null ],
        [ "attr_to_std_helper< std::string >", "structsimics_1_1detail_1_1attr__to__std__helper_3_01std_1_1string_01_4.html", null ],
        [ "attr_to_std_helper< std::vector< V > >", "structsimics_1_1detail_1_1attr__to__std__helper_3_01std_1_1vector_3_01V_01_4_01_4.html", null ],
        [ "attr_type_str_helper", "structsimics_1_1detail_1_1attr__type__str__helper.html", null ],
        [ "attr_type_str_helper< std::array< T, N > >", "structsimics_1_1detail_1_1attr__type__str__helper_3_01std_1_1array_3_01T_00_01N_01_4_01_4.html", null ],
        [ "attr_type_str_helper< std::map< X, Y > >", "structsimics_1_1detail_1_1attr__type__str__helper_3_01std_1_1map_3_01X_00_01Y_01_4_01_4.html", null ],
        [ "attr_type_str_helper< std::pair< X, Y > >", "structsimics_1_1detail_1_1attr__type__str__helper_3_01std_1_1pair_3_01X_00_01Y_01_4_01_4.html", null ],
        [ "attr_type_str_helper< std::vector< uint8 > >", "structsimics_1_1detail_1_1attr__type__str__helper_3_01std_1_1vector_3_01uint8_01_4_01_4.html", null ],
        [ "ConstSizeT", "classsimics_1_1detail_1_1ConstSizeT.html", "classsimics_1_1detail_1_1ConstSizeT" ],
        [ "has_init_class", "structsimics_1_1detail_1_1has__init__class.html", null ],
        [ "has_init_class< T, typename voider< decltype(T::init_class)>::type >", "structsimics_1_1detail_1_1has__init__class_3_01T_00_01typename_01voider_3_01decltype_07T_1_1init__class_08_4_1_1type_01_4.html", null ],
        [ "HierarchicalObjectName", "classsimics_1_1detail_1_1HierarchicalObjectName.html", "classsimics_1_1detail_1_1HierarchicalObjectName" ],
        [ "RegisterInfo", "structsimics_1_1detail_1_1RegisterInfo.html", "structsimics_1_1detail_1_1RegisterInfo" ],
        [ "voider", "structsimics_1_1detail_1_1voider.html", "structsimics_1_1detail_1_1voider" ]
      ] ],
      [ "iface", "namespacesimics_1_1iface.html", [
        [ "ConfObjectInterface", "classsimics_1_1iface_1_1ConfObjectInterface.html", "classsimics_1_1iface_1_1ConfObjectInterface" ],
        [ "InterfaceInfo", "classsimics_1_1iface_1_1InterfaceInfo.html", "classsimics_1_1iface_1_1InterfaceInfo" ],
        [ "ObjectFactoryInterface", "classsimics_1_1iface_1_1ObjectFactoryInterface.html", "classsimics_1_1iface_1_1ObjectFactoryInterface" ]
      ] ],
      [ "AliasRegister", "classsimics_1_1AliasRegister.html", "classsimics_1_1AliasRegister" ],
      [ "Attribute", "classsimics_1_1Attribute.html", "classsimics_1_1Attribute" ],
      [ "AttributeAccessor", "structsimics_1_1AttributeAccessor.html", "structsimics_1_1AttributeAccessor" ],
      [ "Bank", "classsimics_1_1Bank.html", "classsimics_1_1Bank" ],
      [ "BankAccess", "structsimics_1_1BankAccess.html", "structsimics_1_1BankAccess" ],
      [ "BankInstrumentationSubscribeConnection", "classsimics_1_1BankInstrumentationSubscribeConnection.html", "classsimics_1_1BankInstrumentationSubscribeConnection" ],
      [ "BankInterface", "classsimics_1_1BankInterface.html", "classsimics_1_1BankInterface" ],
      [ "BankIssueCallbacksInterface", "classsimics_1_1BankIssueCallbacksInterface.html", "classsimics_1_1BankIssueCallbacksInterface" ],
      [ "BankPort", "classsimics_1_1BankPort.html", "classsimics_1_1BankPort" ],
      [ "BankPortInterface", "classsimics_1_1BankPortInterface.html", "classsimics_1_1BankPortInterface" ],
      [ "BankRegister", "classsimics_1_1BankRegister.html", "classsimics_1_1BankRegister" ],
      [ "BigEndianBank", "classsimics_1_1BigEndianBank.html", "classsimics_1_1BigEndianBank" ],
      [ "ClearOnReadField", "classsimics_1_1ClearOnReadField.html", "classsimics_1_1ClearOnReadField" ],
      [ "ClearOnReadRegister", "classsimics_1_1ClearOnReadRegister.html", "classsimics_1_1ClearOnReadRegister" ],
      [ "ConfClass", "classsimics_1_1ConfClass.html", "classsimics_1_1ConfClass" ],
      [ "ConfObject", "classsimics_1_1ConfObject.html", "classsimics_1_1ConfObject" ],
      [ "ConfObjectRef", "classsimics_1_1ConfObjectRef.html", "classsimics_1_1ConfObjectRef" ],
      [ "Connect", "classsimics_1_1Connect.html", "classsimics_1_1Connect" ],
      [ "ConnectBase", "classsimics_1_1ConnectBase.html", "classsimics_1_1ConnectBase" ],
      [ "ConnectConfig", "classsimics_1_1ConnectConfig.html", "classsimics_1_1ConnectConfig" ],
      [ "ConstantField", "classsimics_1_1ConstantField.html", "classsimics_1_1ConstantField" ],
      [ "ConstantRegister", "classsimics_1_1ConstantRegister.html", "classsimics_1_1ConstantRegister" ],
      [ "DesignLimitationField", "classsimics_1_1DesignLimitationField.html", "classsimics_1_1DesignLimitationField" ],
      [ "DesignLimitationRegister", "classsimics_1_1DesignLimitationRegister.html", "classsimics_1_1DesignLimitationRegister" ],
      [ "Field", "classsimics_1_1Field.html", "classsimics_1_1Field" ],
      [ "FieldInterface", "classsimics_1_1FieldInterface.html", "classsimics_1_1FieldInterface" ],
      [ "HierarchicalObject", "classsimics_1_1HierarchicalObject.html", "classsimics_1_1HierarchicalObject" ],
      [ "HierarchicalObjectInterface", "classsimics_1_1HierarchicalObjectInterface.html", "classsimics_1_1HierarchicalObjectInterface" ],
      [ "IgnoreField", "classsimics_1_1IgnoreField.html", "classsimics_1_1IgnoreField" ],
      [ "IgnoreRegister", "classsimics_1_1IgnoreRegister.html", "classsimics_1_1IgnoreRegister" ],
      [ "IgnoreWriteField", "classsimics_1_1IgnoreWriteField.html", "classsimics_1_1IgnoreWriteField" ],
      [ "IgnoreWriteRegister", "classsimics_1_1IgnoreWriteRegister.html", "classsimics_1_1IgnoreWriteRegister" ],
      [ "InterfaceMap", "classsimics_1_1InterfaceMap.html", null ],
      [ "MapNameToInterface", "classsimics_1_1MapNameToInterface.html", "classsimics_1_1MapNameToInterface" ],
      [ "MapNameToInterfaceObject", "classsimics_1_1MapNameToInterfaceObject.html", "classsimics_1_1MapNameToInterfaceObject" ],
      [ "MapNameToInterfaceObject< RegisterInterface >", "classsimics_1_1MapNameToInterfaceObject_3_01RegisterInterface_01_4.html", "classsimics_1_1MapNameToInterfaceObject_3_01RegisterInterface_01_4" ],
      [ "MappableConfObject", "classsimics_1_1MappableConfObject.html", "classsimics_1_1MappableConfObject" ],
      [ "MissPatternBank", "classsimics_1_1MissPatternBank.html", "classsimics_1_1MissPatternBank" ],
      [ "nocopy", "classsimics_1_1nocopy.html", "classsimics_1_1nocopy" ],
      [ "ObjectFactory", "classsimics_1_1ObjectFactory.html", "classsimics_1_1ObjectFactory" ],
      [ "ObjectFactoryWithArg", "classsimics_1_1ObjectFactoryWithArg.html", "classsimics_1_1ObjectFactoryWithArg" ],
      [ "OnesField", "classsimics_1_1OnesField.html", "classsimics_1_1OnesField" ],
      [ "OnesRegister", "classsimics_1_1OnesRegister.html", "classsimics_1_1OnesRegister" ],
      [ "Port", "classsimics_1_1Port.html", "classsimics_1_1Port" ],
      [ "PortBank", "classsimics_1_1PortBank.html", "classsimics_1_1PortBank" ],
      [ "Read0Field", "classsimics_1_1Read0Field.html", "classsimics_1_1Read0Field" ],
      [ "Read0Register", "classsimics_1_1Read0Register.html", "classsimics_1_1Read0Register" ],
      [ "ReadConstantField", "classsimics_1_1ReadConstantField.html", "classsimics_1_1ReadConstantField" ],
      [ "ReadConstantRegister", "classsimics_1_1ReadConstantRegister.html", "classsimics_1_1ReadConstantRegister" ],
      [ "ReadOnlyClearOnReadField", "classsimics_1_1ReadOnlyClearOnReadField.html", "classsimics_1_1ReadOnlyClearOnReadField" ],
      [ "ReadOnlyClearOnReadRegister", "classsimics_1_1ReadOnlyClearOnReadRegister.html", "classsimics_1_1ReadOnlyClearOnReadRegister" ],
      [ "ReadOnlyField", "classsimics_1_1ReadOnlyField.html", "classsimics_1_1ReadOnlyField" ],
      [ "ReadOnlyRegister", "classsimics_1_1ReadOnlyRegister.html", "classsimics_1_1ReadOnlyRegister" ],
      [ "ReadUnimplField", "classsimics_1_1ReadUnimplField.html", "classsimics_1_1ReadUnimplField" ],
      [ "ReadUnimplRegister", "classsimics_1_1ReadUnimplRegister.html", "classsimics_1_1ReadUnimplRegister" ],
      [ "Register", "classsimics_1_1Register.html", "classsimics_1_1Register" ],
      [ "RegisterField", "classsimics_1_1RegisterField.html", "classsimics_1_1RegisterField" ],
      [ "RegisterInterface", "classsimics_1_1RegisterInterface.html", "classsimics_1_1RegisterInterface" ],
      [ "ReservedField", "classsimics_1_1ReservedField.html", "classsimics_1_1ReservedField" ],
      [ "ReservedRegister", "classsimics_1_1ReservedRegister.html", "classsimics_1_1ReservedRegister" ],
      [ "SilentConstantField", "classsimics_1_1SilentConstantField.html", "classsimics_1_1SilentConstantField" ],
      [ "SilentConstantRegister", "classsimics_1_1SilentConstantRegister.html", "classsimics_1_1SilentConstantRegister" ],
      [ "SilentUnimplField", "classsimics_1_1SilentUnimplField.html", "classsimics_1_1SilentUnimplField" ],
      [ "SilentUnimplRegister", "classsimics_1_1SilentUnimplRegister.html", "classsimics_1_1SilentUnimplRegister" ],
      [ "UndocumentedField", "classsimics_1_1UndocumentedField.html", "classsimics_1_1UndocumentedField" ],
      [ "UndocumentedRegister", "classsimics_1_1UndocumentedRegister.html", "classsimics_1_1UndocumentedRegister" ],
      [ "UnimplField", "classsimics_1_1UnimplField.html", "classsimics_1_1UnimplField" ],
      [ "UnimplRegister", "classsimics_1_1UnimplRegister.html", "classsimics_1_1UnimplRegister" ],
      [ "UnmappedRegister", "classsimics_1_1UnmappedRegister.html", "classsimics_1_1UnmappedRegister" ],
      [ "ValueAccessorInterface", "classsimics_1_1ValueAccessorInterface.html", "classsimics_1_1ValueAccessorInterface" ],
      [ "ValueMutatorInterface", "classsimics_1_1ValueMutatorInterface.html", "classsimics_1_1ValueMutatorInterface" ],
      [ "Write0OnlyField", "classsimics_1_1Write0OnlyField.html", "classsimics_1_1Write0OnlyField" ],
      [ "Write0OnlyRegister", "classsimics_1_1Write0OnlyRegister.html", "classsimics_1_1Write0OnlyRegister" ],
      [ "Write1ClearsField", "classsimics_1_1Write1ClearsField.html", "classsimics_1_1Write1ClearsField" ],
      [ "Write1ClearsRegister", "classsimics_1_1Write1ClearsRegister.html", "classsimics_1_1Write1ClearsRegister" ],
      [ "Write1OnlyField", "classsimics_1_1Write1OnlyField.html", "classsimics_1_1Write1OnlyField" ],
      [ "Write1OnlyRegister", "classsimics_1_1Write1OnlyRegister.html", "classsimics_1_1Write1OnlyRegister" ],
      [ "WriteOnceField", "classsimics_1_1WriteOnceField.html", "classsimics_1_1WriteOnceField" ],
      [ "WriteOnceRegister", "classsimics_1_1WriteOnceRegister.html", "classsimics_1_1WriteOnceRegister" ],
      [ "WriteOnlyRegister", "classsimics_1_1WriteOnlyRegister.html", "classsimics_1_1WriteOnlyRegister" ],
      [ "WriteUnimplField", "classsimics_1_1WriteUnimplField.html", "classsimics_1_1WriteUnimplField" ],
      [ "WriteUnimplRegister", "classsimics_1_1WriteUnimplRegister.html", "classsimics_1_1WriteUnimplRegister" ],
      [ "ZerosField", "classsimics_1_1ZerosField.html", "classsimics_1_1ZerosField" ],
      [ "ZerosRegister", "classsimics_1_1ZerosRegister.html", "classsimics_1_1ZerosRegister" ]
    ] ],
    [ "bank_access", "structbank__access.html", "structbank__access" ]
];