var dir_327a9a05f0684aa9e6dce9f3639b3ca7 =
[
    [ "dmi_transaction_handler.h", "dmi__transaction__handler_8h.html", "dmi__transaction__handler_8h" ],
    [ "error_transaction_handler.h", "error__transaction__handler_8h.html", "error__transaction__handler_8h" ],
    [ "ethernet_common.h", "tlm2simics_2ethernet__common_8h.html", "tlm2simics_2ethernet__common_8h" ],
    [ "gasket.h", "tlm2simics_2gasket_8h.html", "tlm2simics_2gasket_8h" ],
    [ "gasket_class.h", "tlm2simics_2gasket__class_8h.html", "tlm2simics_2gasket__class_8h" ],
    [ "gasket_dispatcher.h", "gasket__dispatcher_8h.html", "gasket__dispatcher_8h" ],
    [ "gasket_factory.h", "tlm2simics_2gasket__factory_8h.html", "tlm2simics_2gasket__factory_8h" ],
    [ "gasket_interface.h", "tlm2simics_2gasket__interface_8h.html", "tlm2simics_2gasket__interface_8h" ],
    [ "gasket_owner.h", "tlm2simics_2gasket__owner_8h.html", "tlm2simics_2gasket__owner_8h" ],
    [ "i2c_master_v2.h", "tlm2simics_2i2c__master__v2_8h.html", "tlm2simics_2i2c__master__v2_8h" ],
    [ "i2c_slave_v2.h", "tlm2simics_2i2c__slave__v2_8h.html", "tlm2simics_2i2c__slave__v2_8h" ],
    [ "i3c_master.h", "tlm2simics_2i3c__master_8h.html", "tlm2simics_2i3c__master_8h" ],
    [ "i3c_slave.h", "tlm2simics_2i3c__slave_8h.html", "tlm2simics_2i3c__slave_8h" ],
    [ "memory_space.h", "memory__space_8h.html", "memory__space_8h" ],
    [ "null_gasket.h", "tlm2simics_2null__gasket_8h.html", "tlm2simics_2null__gasket_8h" ],
    [ "null_transaction_handler.h", "null__transaction__handler_8h.html", "null__transaction__handler_8h" ],
    [ "packet.h", "tlm2simics_2packet_8h.html", "tlm2simics_2packet_8h" ],
    [ "pci_bus.h", "pci__bus_8h.html", "pci__bus_8h" ],
    [ "pci_express.h", "tlm2simics_2pci__express_8h.html", "tlm2simics_2pci__express_8h" ],
    [ "serial_device.h", "tlm2simics_2serial__device_8h.html", "tlm2simics_2serial__device_8h" ],
    [ "spi_slave.h", "spi__slave_8h.html", "spi__slave_8h" ],
    [ "tlm2simics.h", "tlm2simics_8h.html", null ],
    [ "transaction.h", "tlm2simics_2transaction_8h.html", "tlm2simics_2transaction_8h" ],
    [ "transaction_handler.h", "transaction__handler_8h.html", "transaction__handler_8h" ],
    [ "transaction_handler_interface.h", "transaction__handler__interface_8h.html", "transaction__handler__interface_8h" ]
];